"use client";

import { useEffect, useRef, useState } from "react";
import { Camera, X, CheckCircle } from "lucide-react";

// QRScanner Component (integrated directly)
interface QRScannerProps {
  isOpen: boolean;
  onClose: () => void;
  onScan: (data: string) => void;
}

const QRScanner: React.FC<QRScannerProps> = ({ isOpen, onClose, onScan }) => {
  const scannerRef = useRef<any>(null);
  const [isScanning, setIsScanning] = useState(false);
  const [error, setError] = useState<string>("");
  const [Html5Qrcode, setHtml5Qrcode] = useState<any>(null);

  // Dynamically import html5-qrcode
  useEffect(() => {
    if (isOpen && !Html5Qrcode) {
      import("html5-qrcode")
        .then((module) => {
          setHtml5Qrcode(() => module.Html5Qrcode);
        })
        .catch((err) => {
          console.error("Failed to load html5-qrcode:", err);
          setError(
            "Failed to load QR scanner library. Please refresh the page."
          );
        });
    }
  }, [isOpen, Html5Qrcode]);

  useEffect(() => {
    if (isOpen && Html5Qrcode) {
      startScanner();
    }

    return () => {
      stopScanner();
    };
  }, [isOpen, Html5Qrcode]);

  const startScanner = async () => {
    try {
      setError("");

      if (!Html5Qrcode) {
        setError("Scanner not loaded yet. Please wait...");
        return;
      }

      // Initialize scanner
      const scanner = new Html5Qrcode("qr-reader");
      scannerRef.current = scanner;

      // Start scanning
      await scanner.start(
        { facingMode: "environment" },
        {
          fps: 10,
          qrbox: { width: 250, height: 250 },
        },
        (decodedText: any) => {
          console.log("QR Code detected:", decodedText);
          onScan(decodedText);
          stopScanner();
        },
        (errorMessage: any) => {
          // Ignore continuous scanning errors
        }
      );

      setIsScanning(true);
    } catch (err: any) {
      console.error("Error starting scanner:", err);
      setError(
        err?.message || "Failed to access camera. Please check permissions."
      );
    }
  };

  const stopScanner = async () => {
    if (scannerRef.current && isScanning) {
      try {
        await scannerRef.current.stop();
        scannerRef.current.clear();
        scannerRef.current = null;
        setIsScanning(false);
      } catch (err) {
        console.error("Error stopping scanner:", err);
      }
    }
  };

  const handleClose = () => {
    stopScanner();
    onClose();
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
      <div className="bg-white rounded-lg w-full max-w-md">
        <div className="flex items-center justify-between p-4 border-b">
          <h2 className="text-lg font-semibold">Scan QR Code</h2>
          <button
            onClick={handleClose}
            className="text-gray-400 hover:text-gray-600"
          >
            <X size={24} />
          </button>
        </div>

        <div className="p-6">
          {error ? (
            <div className="text-center py-8">
              <div className="text-red-500 mb-4">
                <Camera size={48} className="mx-auto" />
              </div>
              <p className="text-red-600 mb-4">{error}</p>
              <button
                onClick={startScanner}
                className="bg-teal-600 text-white px-6 py-2 rounded-lg hover:bg-teal-700"
              >
                Try Again
              </button>
            </div>
          ) : (
            <>
              <div
                id="qr-reader"
                className="w-full rounded-lg overflow-hidden mb-4"
              ></div>
              <div className="text-center">
                <p className="text-gray-600 text-sm">
                  Position the QR code within the frame to scan
                </p>
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  );
};

// Main Scan Page Component
export const ScanPage = () => {
  const [showScanner, setShowScanner] = useState(false);
  const [scannedData, setScannedData] = useState<any>(null);
  const [showSuccess, setShowSuccess] = useState(false);

  const handleScan = (data: string) => {
    try {
      // Try to parse as JSON (for QR codes generated by the app)
      const parsed = JSON.parse(data);
      setScannedData(parsed);
    } catch (err) {
      // If not JSON, treat as plain text/barcode
      setScannedData({ raw: data, name: data });
    }

    setShowScanner(false);
    setShowSuccess(true);

    // Hide success message after 3 seconds
    setTimeout(() => setShowSuccess(false), 3000);
  };

  return (
    <div className="min-h-screen bg-gray-50 px-4 py-8">
      <div className="max-w-2xl mx-auto">
        {/* Header */}
        <h1 className="text-3xl font-bold text-gray-900 mb-2">Scan Item</h1>

        {/* Main Card */}
        <div className="bg-white rounded-2xl shadow-sm border border-gray-200 p-8 mt-8">
          <div className="flex flex-col items-center">
            {/* QR Code Icon */}
            <div className="w-64 h-64 bg-gray-50 rounded-2xl border-2 border-gray-200 flex items-center justify-center mb-6">
              <svg viewBox="0 0 100 100" className="w-48 h-48">
                {/* Top-left corner */}
                <rect x="10" y="10" width="15" height="15" fill="black" />
                <rect x="30" y="10" width="5" height="15" fill="black" />

                {/* Top-right corner */}
                <rect x="75" y="10" width="15" height="15" fill="black" />
                <rect x="65" y="10" width="5" height="15" fill="black" />

                {/* Bottom-left corner */}
                <rect x="10" y="75" width="15" height="15" fill="black" />
                <rect x="30" y="75" width="5" height="15" fill="black" />

                {/* Center pattern (lighter) */}
                <rect x="45" y="45" width="10" height="5" fill="#999" />
                <rect x="50" y="50" width="5" height="10" fill="#999" />
                <rect x="40" y="55" width="15" height="5" fill="#999" />
                <rect x="60" y="45" width="5" height="15" fill="#999" />

                {/* Bottom-right pattern (lighter) */}
                <rect x="70" y="70" width="8" height="8" fill="#999" />
                <rect x="80" y="75" width="5" height="8" fill="#999" />
                <rect x="75" y="85" width="8" height="5" fill="#999" />
              </svg>
            </div>

            {/* Description */}
            <p className="text-gray-600 text-center mb-8 max-w-md">
              Scan an item's barcode or QR code to check its availability and
              quantity in your inventory
            </p>

            {/* Scan Button */}
            <button
              onClick={() => setShowScanner(true)}
              className="bg-teal-600 hover:bg-teal-700 text-white font-semibold px-8 py-3 rounded-lg transition-colors flex items-center gap-2 shadow-sm"
            >
              <Camera size={20} />
              Scan Item
            </button>
          </div>
        </div>

        {/* Success Message */}
        {showSuccess && (
          <div className="mt-6 bg-green-50 border border-green-200 rounded-lg p-4 flex items-center gap-3 animate-fade-in">
            <CheckCircle className="text-green-600" size={24} />
            <div>
              <p className="text-green-900 font-semibold">
                Successfully scanned!
              </p>
              <p className="text-green-700 text-sm">Processing item data...</p>
            </div>
          </div>
        )}

        {/* Scanned Item Result */}
        {scannedData && (
          <div className="mt-6 bg-white border border-gray-200 rounded-lg p-6 shadow-sm">
            <h3 className="font-semibold text-gray-900 mb-4 text-lg">
              Scanned Item Details:
            </h3>
            <div className="space-y-2">
              <div className="flex justify-between py-2 border-b">
                <span className="text-gray-600">Name:</span>
                <span className="font-medium text-gray-900">
                  {scannedData.name || "N/A"}
                </span>
              </div>
              {scannedData.id && (
                <div className="flex justify-between py-2 border-b">
                  <span className="text-gray-600">ID:</span>
                  <span className="font-mono text-sm text-gray-900">
                    {scannedData.id}
                  </span>
                </div>
              )}
              {scannedData.timestamp && (
                <div className="flex justify-between py-2 border-b">
                  <span className="text-gray-600">Created:</span>
                  <span className="text-sm text-gray-900">
                    {new Date(scannedData.timestamp).toLocaleDateString()}
                  </span>
                </div>
              )}
              {scannedData.raw && (
                <div className="flex justify-between py-2">
                  <span className="text-gray-600">Raw Data:</span>
                  <span className="font-mono text-xs text-gray-900 break-all max-w-xs">
                    {scannedData.raw}
                  </span>
                </div>
              )}
            </div>

            {/* Action Buttons */}
            <div className="flex gap-3 mt-6">
              <button className="flex-1 bg-teal-600 text-white py-2 rounded-lg hover:bg-teal-700 transition-colors">
                Check Inventory
              </button>
              <button className="flex-1 bg-gray-100 text-gray-700 py-2 rounded-lg hover:bg-gray-200 transition-colors">
                View Details
              </button>
            </div>
          </div>
        )}
      </div>

      {/* QR Scanner Modal */}
      <QRScanner
        isOpen={showScanner}
        onClose={() => setShowScanner(false)}
        onScan={handleScan}
      />
    </div>
  );
};
